black:
  max:
  - 130
  - 130
  - 179
  min:
  - 92
  - 127
  - 123
blue:
  max:
  - 151
  - 157
  - 121
  min:
  - 101
  - 98
  - 91
green:
  max:
  - 255
  - 110
  - 255
  min:
  - 47
  - 0
  - 135
red:
  max:
  - 167
  - 206
  - 147
  min:
  - 113
  - 134
  - 127
